apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpe.fullname" . }}-akka-conf
data:
  akka.hocon: |
    akka {
      actor.provider = cluster
      loglevel = DEBUG
      stdout-loglevel = DEBUG

      remote.dot-netty.tcp {
        hostname = "0.0.0.0"
        port = {{ .Values.akkaOptions.remoteOptions.port | default 4051 }}
      }

      discovery {
        method = aggregate
        aggregate.discovery-methods = [kubernetes-api, config]

        kubernetes-api {
          class = "Akka.Discovery.KubernetesApi.KubernetesApiServiceDiscovery, Akka.Discovery.KubernetesApi"
          api-ca-path = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          api-token-path = "/var/run/secrets/kubernetes.io/serviceaccount/token"
          api-service-host-env-name = "KUBERNETES_SERVICE_HOST"
          api-service-port-env-name = "KUBERNETES_SERVICE_PORT"
          pod-namespace-path = "/var/run/secrets/kubernetes.io/serviceaccount/namespace"
          pod-namespace = "{{ .Release.Namespace }}"
          pod-domain = "cluster.local"
          pod-label-selector = "cluster=nucleus-rule-services"
          use-raw-ip = true
          container-name = ""
        }

        config {
          class = "Akka.Discovery.Config.ConfigServiceDiscovery, Akka.Discovery"
          services {}
        }
      }

      cluster.bootstrap.contact-point-discovery {
        service-name = "nucleus-rule-services"
        required-contact-point-nr = {{ default 1 .Values.akkaOptions.clusterOptions.requiredContactPointNr }}
      }

      cluster {
        log-info = on
        downing-provider-class = "Akka.Cluster.SBR.SplitBrainResolverProvider, Akka.Cluster"
        split-brain-resolver {
          active-strategy = keep-majority
          stable-after = 20s
          down-all-when-unstable = on
        }
      }
    }

    petabridge.cmd {
      host = "0.0.0.0"
      port = 9110
      log-info = on
    }
