apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpe.fullname" . }}-akka-conf
data:
  akka.hocon: |
    akka {
      actor.provider = cluster

      remote.dot-netty.tcp {
        hostname = "0.0.0.0"
        port = {{ .Values.akkaOptions.remoteOptions.port | default 4051 }}
      }

      discovery {
        method = kubernetes-api

        kubernetes-api {
          class = "Akka.Discovery.KubernetesApi.KubernetesApiServiceDiscovery, Akka.Discovery.KubernetesApi"
          pod-namespace = "{{ .Release.Namespace }}"
        }
      }

      cluster.bootstrap.contact-point-discovery {
        service-name = "{{ printf "%s-akka" (include "cpe.fullname" .) }}"
        discovery-method = kubernetes-api
        required-contact-point-nr = {{ default 1 .Values.akkaOptions.clusterOptions.requiredContactPointNr }}
      }

      cluster {
        downing-provider-class = "Akka.Cluster.SBR.SplitBrainResolverProvider, Akka.Cluster"
        split-brain-resolver {
          active-strategy = keep-majority
          stable-after = 20s
          down-all-when-unstable = on
        }
      }
    }
