apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpe.fullname" . }}-akka-variables
  labels:
    {{ include "cpe.labels" . | nindent 4 }}
data:
  SEED_NODES: '{{- if and (index .Values "akkaOptions") (index (index .Values "akkaOptions") "clusterOptions") (index (index (index .Values "akkaOptions") "clusterOptions") "seedNodes") -}}{{ index (index (index .Values "akkaOptions") "clusterOptions") "seedNodes" 0 -}}{{ else -}}{{ "" -}}{{- end }}'

  AkkaOptions__ClusterName: '{{ .Values.akkaOptions.clusterName | default "" }}'
  AkkaOptions__RemoteOptions__HostName: '{{ .Values.akkaOptions.remoteOptions.hostName | default "" }}'
  AkkaOptions__RemoteOptions__Port: '{{ .Values.akkaOptions.remoteOptions.port | default "" }}'
  AkkaOptions__RemoteOptions__PublicPort: '{{ .Values.akkaOptions.remoteOptions.publicPort | default "" }}'
  AkkaOptions__RemoteOptions__SendBufferSize: '{{ .Values.akkaOptions.remoteOptions.sendBufferSize | default "" }}'
  AkkaOptions__RemoteOptions__ReceiveBufferSize: '{{ .Values.akkaOptions.remoteOptions.receiveBufferSize | default "" }}'
  AkkaOptions__RemoteOptions__MaxFrameSize: '{{ .Values.akkaOptions.remoteOptions.maxFrameSize | default "" }}'
  AkkaOptions__ClusterOptions__LogInfo: '{{ .Values.akkaOptions.clusterOptions.logInfo | default "" }}'
  AkkaOptions__ClusterOptions__ClusterReadyCheck: '{{ .Values.akkaOptions.clusterOptions.clusterReadyCheck | default "" }}'

  AkkaOptions__Discovery__Method: "kubernetes-api"
  AkkaOptions__Cluster__Bootstrap__ContactPointDiscovery__ServiceName: "{{ printf "%s-akka" (include "cpe.fullname" .) }}"
  AkkaOptions__Cluster__Bootstrap__ContactPointDiscovery__RequiredContactPointNr: '{{ .Values.akkaOptions.clusterOptions.requiredContactPointNr | default "1" }}'

  {{ include "cpe.akkaOptionsSeedNodes" . | nindent 2 }}
