{{- range $idx, $d := .Values.deployments }}
{{- if $d.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "cpe.fullname" $) $d.name }}
  labels:
    app: {{ printf "%s-%s" (include "cpe.fullname" $) $d.name }}
    cluster: nucleus-rule-services
    {{- include "cpe.labels" $ | nindent 4 }}
spec:
  replicas: {{ $d.replicaCount | default 3 }}
  selector:
    matchLabels:
      app: {{ printf "%s-%s" (include "cpe.fullname" $) $d.name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" (include "cpe.fullname" $) $d.name }}
        cluster: nucleus-rule-services
        {{- include "cpe.labels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cpe.serviceAccountName" $ }}
      containers:
        - name: {{ printf "%s-%s" (include "cpe.fullname" $) $d.name }}
          image: {{ printf "%s/%s:%s" $.Values.image.repository $d.name $.Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
{{- range $pname, $p := $d.ports }}
            - containerPort: {{ $p }}
              name: {{ $pname }}
{{- end }}
          envFrom:
            - secretRef:
                name: {{ include "cpe.fullname" $ }}-secrets
            - configMapRef:
                name: {{ include "cpe.fullname" $ }}-env-variables
          env:
{{- if $d.env }}
{{ toYaml $d.env | indent 12 }}
{{- end }}
            - name: AkkaOptions__RemoteOptions__PublicHostName
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: Logging__LogLevel__Akka
              value: "Debug"
          volumeMounts:
{{- if $.Values.volumeMounts }}
{{ toYaml $.Values.volumeMounts | indent 12 }}
{{- else }}
            - name: akka-conf
              mountPath: /app/akka.hocon
              subPath: akka.hocon
{{- end }}
          resources:
{{ toYaml $d.resources | indent 12 }}
      volumes:
        - name: cpe-volume-tns
          secret:
            secretName: {{ include "cpe.fullname" $ }}-tns
            optional: false
{{- if $.Values.volumes }}
{{ toYaml $.Values.volumes | nindent 8 }}
{{- else }}
        - name: akka-conf
          configMap:
            name: {{ include "cpe.fullname" $ }}-akka-conf
            optional: true
{{- end }}
---
{{- end }}
{{- end }}
