{{- range .Values.secrets }}
  {{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "cpe.fullname" $) .name }}
  labels:
    {{- include "cpe.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}