apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-akka" (include "cpe.fullname" .) }}
  labels:
    {{- include "cpe.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "cpe.selectorLabels" . | nindent 4 }}
  ports:
    - name: akka-4051
      port: {{ .Values.akkaOptions.remoteOptions.port | default 4051 }}
      targetPort: {{ .Values.akkaOptions.remoteOptions.port | default 4051 }}
      protocol: TCP
