# Default values for cpe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: artifactory.cotiviti.com/adlm-sandbox-docker/sandbox/poc
  tag: newtest

secrets:
  - name: secrets
    enabled: true
    data: {}

appsettings:
  Logging__LogLevel__Default: "Debug"
  RedisConfiguration__PoolSize: "2"
  RedisConfiguration__Hosts__0__Host: "w1q01-cpered01.mediconnect.net"
  RedisConfiguration__Hosts__0__Port: "6379"
  RedisConfiguration__Hosts__1__Host: "w1q01-cpered01.mediconnect.net"
  RedisConfiguration__Hosts__1__Port: "6380"
  RedisConfiguration__Password: "ubYFiiG1DjO4"
  Logging__LogLevel__Microsoft: "Information"
  ApplicationSettings__SupportEmail: "cpe_dev@cotiviti.com"
  ApplicationSettings__KibanaCorrelationIdUrl: ""
  ApplicationSettings__AesKey: "496F3491AA7B8CE9AAD8BE64A72BBDC4"

  # BatchProcessor specific
  ApplicationSettings__DispatcherChunkSize: "80"
  ApplicationSettings__RecurringMessageInterval: "60"
  ApplicationSettings__PgpKeyLocation: ""
  ApplicationSettings__PgpInternalEncryptFingerprint: ""
  ApplicationSettings__ReturnFilePickupLocation: ""

  # BatchPortal specific
  ApplicationSettings__AllowBatchSeqInput: "true"
  ASPNETCORE_URLS: http://*:8080
  ASPNETCORE_HTTP_PORT: "8080"

akkaOptions:
  remoteOptions:
    port: 4051
  clusterOptions:
    requiredContactPointNr: 1

services:
  batchportal:
    enabled: true
    ports:
      akka: 4051
      pbm: 9110
      http: 8080
  editorservice:
    enabled: true
    ports:
      akka: 4051
      pbm: 9110
  batchprocessor:
    enabled: true
    ports:
      akka: 4051
      pbm: 9110

service:
  type: ClusterIP
  port: 8080

deployments:
  - name: batchportal
    enabled: true
    replicaCount: 1
    ports:
      pbm: 9110
      http: 8080
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: editorservice
    enabled: true
    replicaCount: 1
    ports:
      pbm: 9110
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  - name: batchprocessor
    enabled: true
    replicaCount: 1
    ports:
      pbm: 9110
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

route:
  enabled: true
  hostname: apps.openshift-nonprod.cotiviti.com
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  routes:
    - name: batchportal
      host: cpe-batch-portal

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


