# Default values for cpe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  #repository: localhost:32000
  repository: artifactory.cotiviti.com/ppm-nucleus-docker/sandbox/cpe
  tag: 2026.3.4-alpha.CPP-52910-akka-hosting.17

secrets:
  - name: tns
    enabled: true
    data:
      tnsnames.ora: REJRQT0oREVTQ1JJUFRJT049KEFERFJFU1M9KFBST1RPQ09MPVRDUCkoSE9TVD0xMC4xMjguMTk0LjIwNCkoUE9SVD0xNTIxKSkoQ09OTkVDVF9EQVRBPShTRVJWRVI9ZGVkaWNhdGVkKShTRVJWSUNFX05BTUU9ZGJxYSkpKQ0KUU5VQ0E9KERFU0NSSVBUSU9OPShBRERSRVNTPShQUk9UT0NPTD1UQ1ApKEhPU1Q9MTAuMTI4LjE5NC4yMDQpKFBPUlQ9MTUyMSkpKENPTk5FQ1RfREFUQT0oU0VSVkVSPWRlZGljYXRlZCkoU0VSVklDRV9OQU1FPXFudWNhLmhjaW5zaWdodC5uZXQpKSkNCg==

  - name: secrets
    enabled: true
    data:
      OracleSettings__Connection__Password: bW9uZGF5

appsettings:

  TNS_ADMIN: "/tns"

  # BatchPortal, BatchProcessor, CpeServiceWebApi, EditorService
  OracleSettings__Connection__DataSource: "QNUCA"
  Logging__LogLevel__Default: "Debug"
  Logging__LogLevel__Microsoft: "Information"
  RedisConfiguration__PoolSize: "2"
  RedisConfiguration__Hosts__0__Host: "w1q01-cpered01.mediconnect.net"
  RedisConfiguration__Hosts__0__Port: "6379"
  redisConfiguration__Hosts__1__Host: "w1q01-cpered01.mediconnect.net"
  RedisConfiguration__Hosts__1__Port: "6380"
  ApplicationSettings__SupportEmail: "cpe_dev@cotiviti.com"
  ApplicationSettings__KibanaCorrelationIdUrl: ""
  RedisConfiguration__Password: "ubYFiiG1DjO4"
  ApplicationSettings__AesKey: "496F3491AA7B8CE9AAD8BE64A72BBDC4" #"496F3491AA7B8CE9AAD8BE64A72BBDC4"

  # BatchProcessor
  ApplicationSettings__DispatcherChunkSize: "80"
  ApplicationSettings__RecurringMessageInterval: "60"
  ApplicationSettings__PgpKeyLocation: "" #"c:\\pgp"
  ApplicationSettings__PgpInternalEncryptFingerprint: "" #"FFAF41393F81A6D7C49E8AB7334A3C7497C8699E"
  ApplicationSettings__ReturnFilePickupLocation: "" #"\\\\W1Q01-CPEBP01.mediconnect.net\\shared\\batch-processing"

  # BatchPortal and CpeServiceWebApi
  ApplicationSettings__AllowBatchSeqInput: "true"
  ASPNETCORE_URLS: http://*:8080
  ASPNETCORE_HTTP_PORT: "8080"
  # ASPNETCORE_HTTPS_PORT: "8081"

akkaOptions:
  clusterName: "BatchProcessingSystem"
  remoteOptions:
    hostName: "0.0.0.0"
    port: 0
    publicPort: 0
    sendBufferSize: "4096000"
    receiveBufferSize: "4096000"
    maxFrameSize: "4096000"
  clusterOptions:
    logInfo: false
    clusterReadyCheck: true

lighthouse:
  enabled: true
  replicas: 2
  logLevel: "Debug"
  resources:
    limits:
      cpu: 50m
      memory: 500Mi
    requests:
      cpu: 30m
      memory: 150Mi

services:
  lighthouse:
    enabled: true
    headless: true
    ports:
      akka: 4051
      pbm: 9110
  batchportal:
    enabled: true
    ports:
      pbm: 9110
      http: 8080
      # https: 8081
  webapi:
    enabled: true
    ports:
      http: 8080
      # https: 8081

deployments:
  - name: batchportal
    enabled: true
    replicaCount: 1
    akkaRole: "portal"
    ports:
      pbm: 9110
      http: 8080
    resources:
      limits:
        cpu: 300m
        memory: 800Mi
      requests:
        cpu: 250m
        memory: 600Mi
  - name: webapi
    enabled: true
    replicaCount: 4
    ports:
      http: 8080
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 400m
        memory: 400Mi
  - name: editorservice
    enabled: true
    replicaCount: 4
    akkaRole: "editors"
    ports:
      pbm: 9110
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 1.5Gi
  - name: batchprocessor
    enabled: true
    replicaCount: 1
    akkaRole: "batchprocessor"
    ports:
      pbm: 9110
    resources:
      limits:
        cpu: 1500m
        memory: 8Gi
      requests:
        cpu: 1000m
        memory: 6Gi


route:
  enabled: true
  hostname: apps.openshift-nonprod.cotiviti.com
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  routes:
    - name: batchportal
      host: cpe-batch-portal
    - name: webapi
      host: cpe-web-api


# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
# fsGroup: 2000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
#   cpu: 100m
#   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: cpe-volume-tns
    mountPath: /tns
    readOnly: true
